baseurl = "https://jystatistics.netlify.com//"
languageCode = "en-us"
title = "Welcome to Jongyun Jung's Website"
theme = "hugo-lithium"
googleAnalytics = "UA-121054369-1"
disqusShortname = "http-jystatistics-rbind-io"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
[social]
    github  = "https://github.com/rstudio/jystatistics"
    twitter = "https://twitter.com/jungjongyun83"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Blog"
    url = "/post/"
[[menu.main]]
    name = "Tags"
    url = "/tags/"
[[menu.main]]
    name = "CV"
    url = "/CV/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/jystatistics"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/jungjongyun83"

[params]
    description = "Welcome to Jongyun Jung's Website."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

